version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade awscli
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=<aws-IAM-ac-id>.dkr.ecr.ap-south-1.amazonaws.com/cicd-pipeline-test
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=latest

  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building the Docker image..."
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Pushing the Docker images..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Updating Lambda Function..."
      - aws lambda update-function-code --function-name codebuildtest-mahesh --image-uri <aws-IAM-ac-id>.dkr.ecr.ap-south-1.amazonaws.com/cicd-pipeline-test:latest
      - echo "DONE!!"
